version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "5000:5000"
    depends_on:
      - service-b

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "6000:6000"
