apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-b
spec:
  serviceName: "service-b"
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: ashwini071/service-b:latest
        ports:
        - containerPort: 6000
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - port: 6000
    targetPort: 6000
